// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://detxupzmttiduswldkob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHh1cHptdHRpZHVzd2xka29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTk5NjcsImV4cCI6MjA1OTA3NTk2N30.eNZbqRZybLt6113YRv4RDdTONKXSKEvOikBGLczksyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);